style: cleanup bootstrapper

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -2,24 +2,28 @@
 
 # Changing the hostname if requested to do so
 while true; do
-  printf 'Do you want me to change the hostname of this machine? (y/n) ' 
+  printf 'Do you want me to change the hostname of this machine? (y/n) '
   read -r -n 1 reply
 
-  case $reply in 
-    [yY])
-      printf '\nWhich short hostname should I set? ' 
-      read -r myhostname
-      sudo scutil --set ComputerName "${myhostname}"
-      sudo scutil --set HostName "${myhostname}"
-      sudo scutil --set LocalHostName "${myhostname}"
-      sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string "${myhostname}"
-      printf '\nHostname set to %s\n' "${myhostname}"
-      break;;
-    [n/N])
-      printf '\nSkipping hostname setup\n'
-      break;;
-    *)
-      printf " $(tput setaf 124)invalid response$(tput sgr0)\n";;
+  case $reply in
+  [yY])
+    printf '\nWhich short hostname should I set? '
+    read -r myhostname
+    sudo scutil --set ComputerName "${myhostname}"
+    sudo scutil --set HostName "${myhostname}"
+    sudo scutil --set LocalHostName "${myhostname}"
+    sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string "${myhostname}"
+    printf '\nHostname set to %s\n' "${myhostname}"
+    break
+    ;;
+  [n/N])
+    printf '\nSkipping hostname setup\n'
+    break
+    ;;
+  *)
+    # shellcheck disable=SC2059
+    printf " $(tput setaf 124)invalid response$(tput sgr0)\n"
+    ;;
   esac
 done
 
@@ -29,15 +33,14 @@ pip3_os="/usr/bin/python3 -m pip"
 printf '\nChecking Xcode CLI tools\n'
 # Only run if the tools are not installed yet
 # To check that try to print the SDK path
-xcode-select -p &> /dev/null
-if [ $? -ne 0 ]; then
+if ! xcode-select -p &>/dev/null; then
   printf 'Xcode CLI tools not found. Installing them...\n'
   touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
   PROD=$(softwareupdate -l |
     grep "\*.*Command Line" |
     tail -n 1 | sed 's/^[^C]* //')
-  softwareupdate -i "$PROD" --verbose;
-  touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress;
+  softwareupdate -i "$PROD" --verbose
+  touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
 else
   printf 'Xcode CLI tools OK\n'
 fi
@@ -48,12 +51,11 @@ $pip3_os install --user --upgrade pip
 
 printf '\nInstalling required packages\n'
 pkg_list=$($pip3_os list)
-for pkg in ansible ansible-lint molecule paramiko yamllint; do
-  [[ "$pkg_list" =~ ${pkg}[[:space:]] ]] || \
-    ( printf 'Installing %s\n' "${pkg}" && $pip3_os install --user $pkg)
+for pkg in ansible ansible-lint paramiko yamllint; do
+  [[ "$pkg_list" =~ ${pkg}[[:space:]] ]] ||
+    (printf 'Installing %s\n' "${pkg}" && $pip3_os install --user $pkg)
 done
 printf 'Installed all required packpages\n'
-
 
 printf '\nConfiguring the current shell\n'
 if [ "$SHELL" = /bin/zsh ]; then
@@ -67,7 +69,7 @@ if [ ! -f "$shell_config" ]; then
 fi
 
 if ! grep "Library/Python" ~/.zshrc &>/dev/null; then
-  echo "export PATH=~/Library/Python/3.9/bin/:$PATH" >> "$shell_config"
+  echo "export PATH=~/Library/Python/3.9/bin/:$PATH" >>"$shell_config"
 fi
 
 if ! command -v ansible &>/dev/null; then
